import { useState } from 'react';
import './App.css';
import axios from 'axios';

function App() {
  const BASE_URL = 'https://gemini-clone-backend-93dm.onrender.com';

  const [promptText, setPromptText] = useState('');
  const [responseText, setResponseText] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function handleClick() {
    if (!promptText.trim()) {
      setError('Please enter a prompt first.');
      return;
    }

    setLoading(true);
    setError('');
    setResponseText('');

    try {
      const res = await axios.post(`${BASE_URL}/generate`, {
        text: promptText
      });

      setResponseText(res.data.response);
    } catch (err) {
      setError('Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  function handleKeyDown(event) {
    if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) {
      handleClick();
    }
  }

  async function copyResponse() {
    if (responseText) {
      await navigator.clipboard.writeText(responseText);
    }
  }

  return (
    <div className="app">

      {/* Background decoration */}
      <div className="gradient gradient-1"></div>
      <div className="gradient gradient-2"></div>

      <main className="container">

        {/* Header */}
        <header className="header">
          <div className="logo">
            <div className="logo-icon">✦</div>
            <span>Gemini Clone</span>
          </div>

          <div className="status">
            <span className="status-dot"></span>
            AI Online
          </div>
        </header>

        {/* Hero */}
        <section className="hero">
          <p className="welcome">Welcome to your AI assistant</p>

          <h1>
            What can I help you
            <span> with today?</span>
          </h1>

          <p className="subtitle">
            Ask anything. Generate ideas, solve problems, write code,
            or explore new topics.
          </p>
        </section>

        {/* Prompt Card */}
        <section className="prompt-card">

          <textarea
            value={promptText}
            onChange={(e) => setPromptText(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask me anything..."
          />

          <div className="prompt-footer">

            <span className="shortcut">
              Ctrl + Enter to generate
            </span>

            <button
              className="generate-btn"
              onClick={handleClick}
              disabled={loading}
            >
              {loading ? (
                <>
                  <span className="spinner"></span>
                  Generating...
                </>
              ) : (
                <>
                  Generate
                  <span className="arrow">→</span>
                </>
              )}
            </button>

          </div>

        </section>

        {/* Error */}
        {error && (
          <div className="error-box">
            ⚠ {error}
          </div>
        )}

        {/* Response */}
        {responseText && (
          <section className="response-card">

            <div className="response-header">

              <div className="response-title">
                <div className="ai-icon">✦</div>
                <div>
                  <h2>AI Response</h2>
                  <span>Generated by Gemini</span>
                </div>
              </div>

              <button
                className="copy-btn"
                onClick={copyResponse}
              >
                Copy
              </button>

            </div>

            <div className="response-content">
              {responseText}
            </div>

          </section>
        )}

        {/* Footer */}
        <footer>
          <span>Gemini Clone</span>
          <span>•</span>
          <span>Powered by AI</span>
        </footer>

      </main>
    </div>
  );
}

export default App;